---
title: ""
author: ""
date: ""
output: html_fragment
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<h3 style="text-align: center;">**Statistics related**</h3>

<p style="font-size:20px;"> 
<font size = "4">

PlotS is a data analysis tool that places a strong emphasis on visual representations of data. It doesn't offer standalone statistical analysis; instead, statistical methods can only be applied once a graph or visualization is chosen.

Currently there are four commonly used statistical methods:

A. Parameteric methods: 


1. **T-test** - Welch's and Student's test

2. **ANOVA** - one-way and two-way ANOVA. 
<!-- for type i/ii/iii ss : https://www.r-bloggers.com/2011/03/anova-%E2%80%93-type-iiiiii-ss-explained/ -->


B. Non-parametric methods:

1. **Wilcoxon test** - Rank sum test (Mann Whitney U test) and Signed-rank test

2. **Kruskal-Wallis test**: It is an alternative to one-way ANOVA test and recommended when the assumptions for the parametric test are not met.


</font>
</p>


<br>

<h4> **T-test** </h4>

<p style="font-size:20px;"> 
<font size = "4">

T-test is for comparing means between two groups. If data has more than two variables to compare, it will prompt a warning message to continue or stop the computation. If the decision to proceed is made, the default operation will involve computing statistics for all possible combinations of two variables per group. However, users can later edit the variables for comparison or add reference group to compare.


**_Steps to compare between variables in a group:_**
 
 - **Compare or add reference**: From the options in the **Compare or add reference** menu, select the **comparison**.
 
 - **Choose 2 variables per group**: Users are required to choose two variables from the provided list for comparison.
 
 - **Add**: After selecting the variables, clicking the **Add** button incorporates the chosen pairing into the analysis, which will be reflected in the graph as well as in the **Summary** section. If additional comparisons are desired, users should re-select two variables under **Choose 2 variables per group** and use the **Add** button.
 
 
 - **Delete**: If users wish to remove comparison group, the **Delete** button lets them remove the group sequentially from the comparison list.
 
 
 **_Steps to add reference group:_**
 
 - **Compare or add reference**: Select **reference group** from the menu.
 
 - **Choose 1 variable as reference**: Select the variable to be used as reference. User can add only one variable as reference. If the choosen reference variable is other than **all**, it will perform comparisons by individually contrasting each group level against the selected reference variable. Otherwise, it will conduct pairwise two-sample tests for each grouping variable level against the overall reference (i.e. basemean). 
 
 - **Add** and **Delete**: Use these button to add or delete the reference variable.

</font>
</p>

<br>


<h4> **ANOVA** </h4>

<p style="font-size:20px;"> 
<font size = "4">

Use ANOVA to compare variances across the means of different groups. Two types of ANOVA:

1. **One-way ANOVA**: Select the one-way ANOVA from **ANOVA type**.


2. **Two-way ANOVA**:

   - **ANOVA type**: Select the two-way ANOVA
        
   - **Model** :
        
        i. **Additive**: The outcome of a change in one variable does not depend on the level of other variable, i.e. no interaction.
        ii. **Non-additive**: There is interaction between the factors.
    


**Visualization of ANOVA** 

- **Choose ANOVA figure**: Depending on the model, the list can be **Main effect** and/or **Interaction**

- **Customizing color of variables**: 

  i. **Additive**: A separate color button will be provided for the main effects. Users can edit the color.
        
  ii. **Non-additive**: All paramters supplied using **Aesthetic options** will be applied to **Interaction** figure, but a separate button will be provided for the main effect.
                

**Post-hoc analysis for ANOVA: Tukey's Honest Significant Difference test**

_Note: Currently, PlotS use type I sum of squares._

</font>
</p>

<br>


<h4>**Wilcoxon test**</h4>

<p style="font-size:20px;"> 
<font size = "4">
It is a non-parametric tests for comparing two groups. If there are more than two groups in the data, it will issue a warning message, giving the user the option to proceed with or halt the computation. Similar to the t-test, when user choose to proceed, it will automatically analyze all possible pairs of variables. Users can customize the analysis by adding groups for comparison. The steps for adding groups to compare are analogous to those used in the **t-test**.


**Paired or Unpaired data**:

- Paired data: If the test is to compare two related samples or paired data, then it will use **Wilcoxon signed-rank test**

- Unpaired data: **Mann-Whitney test/ Wilcoxon Rank Sum test** is used for unpaired data.

</font>
</p>


<br>

<h4>**Kruskal-Wallis test**</h4>

<p style="font-size:20px;"> 
<font size = "4">

It is a non-parametric statistical test for analyzing the differences of multiple groups. In PlotS, it can also be employed for analysis of just two groups. Dunn's test is used for post-hoc analysis.

</font>
</p>

<h4 style = color:red;>**Statistic results**</h4>

<p style="font-size:20px;"> 
<font size = "4">
All results related to statistic of the data will be displayed in the **Summary** section. The result can be downloaded as report or individual table and figure (if applicable).

**Tables and figures**:

- **Summary of the input data**: Upon selecting or importing the data, a concise summary of the dataset will be displayed..

- **Descriptive statistics**: Descriptive statistics will be calculated based on the following conditions:

     i. If the user selects a variable for the **X-axis**, the statistics will be computed for that variable.

     ii. If the **Aesthetic options** is active and the selected variable is different from the one chosen for the **X-axis**, the statistics will be computed for the combination of the **X-axis** variable and the **Aesthetic options**.

     Consequently, these statistics will be presented only after the user has selected and configured the graph.



- **Figures**: When employing parametric statistical methods, three graphical representations are provided to assess the assumptions.

  i. **Residuals vs Fitted plot**
  
  ii. **Density plot**
  
  iii. **Normal Q-Q plot**
  
- **Result of normality and homoscedasticity test**: This information is presented exclusively for parametric tests.

- **Summary of statistic result**: It will display the result of selected statistical method.

- **Effect size** : For parametric methods, users can select from various computation methods for effect size. In contrast, non-parametric methods allow only the adjustment of the bootstrap settings.

- **Post-Hoc analysis**: Post-hoc analysis is conducted only for ANOVA and Kruskal-Wallis tests.

</font>
</p>
